services:

  postgres:
    image: postgres:16-alpine
    container_name: app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  backend-service:
    build:
      context: ./backend-service
    container_name: backend-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: backenddb
      DB_USERNAME: backenddb_user
      DB_PASSWORD: ${BACKENDDB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: 3600
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - app-net
    
  frontend-service:
    build:
      context: ./frontend-service
    container_name: frontend-service
    ports:
      - "8080:8080"
    depends_on:
      - backend-service
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
